name: Main

on:
  push:
    branches: [main, release/*]
  schedule:
    - cron: "0 8,20 * * 6"

jobs:
  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    timeout-minutes: 3
    with:
      enable_windows_checks: false
      enable_macos_checks: true
      swift_flags: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      swift_nightly_flags: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
