name: Pull Request Validation (CI)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: hdtls/swift-ci/.github/workflows/soundness.yml@main

  unit-tests:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests.yml@main
    with:
      macos_5_9_enabled: true
      macos_5_10_enabled: true
      macos_6_0_enabled: true
      macos_6_1_enabled: true
      macos_6_2_enabled: true
      macos_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"

      linux_5_9_enabled: true
      linux_5_10_enabled: true
      linux_6_0_enabled: true
      linux_6_1_enabled: true
      linux_6_2_enabled: true
      linux_nightly_release_enabled: true
      linux_nightly_main_enabled: true
      linux_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_nightly_release_build_command_options: "--explicit-target-dependency-import-check warn"
      linux_nightly_main_build_command_options: "--explicit-target-dependency-import-check error"
