name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Setup Swift to 5.7
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.7
    
    - uses: actions/checkout@v3
    
    - name: Build & test...
      run: swift test --parallel
