name: Pull Request Validation (CI)

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - release/*
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: pull request validation (${{ matrix.swift-version }}-${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift-version: ["6.0"]

    steps:
      - name: Checkout repository...
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup swift ${{ matrix.swift-version  }}
        uses: hdtls/setup-swift@main
        with: 
          swift-version: ${{matrix.swift-version}}

      - name: Build and test...
        run: swift test -Xswiftc -warnings-as-errors
